### ISSUE TITLE
Issue during confirming email

### ISSUE THREAD

**Issue by v2karora** [go-authboss/authboss#109]
1) When clicking link in email "=" converts to "%3D" automatically and
2) on localhost it turns to problem loading page (tried 127.0.0.1 as well)
however, if %3D remove from url then it throws error token failed to decode means something is missing during its setup. using qor-sample so it should work out of the box

**Comment by aarondl** [comment]
@v2karora I'm not sure this is an authboss issue. Because if it were then we'd see it in the sample which we're not seeing. %3D is a proper escape and that URL should be fine.

Can you tell me more about the error you're experiencing when this happens? Is it a 404? 500? Is there any stack traces?

**Comment by v2karora** [comment]
Here you go Stack Trace:

github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHT
TP(0xc042b00d70, 0xeb05a0, 0xc043234410, 0xc04328c4b0)
        <autogenerated>:124 +0x80
net/http.(*ServeMux).ServeHTTP(0xc042b040f0, 0xeb05a0, 0xc043234410, 0xc04328c4b
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042b040c0, 0xeb05a0, 0xc043234410, 0xc04328c4b
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042af7fb0, 0xeb05a0, 0xc043234410, 0xc04328c4b
0)
        C:/Go/src/net/http/server.go:2022 +0x86
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc04317bc20, 0xeb05a0, 0xc043234410,
0xc04328c4b0)
        C:/Go/Projects/src/github.com/gorilla/csrf/csrf.go:267 +0x3c1
main.main.func1.1(0xeb05a0, 0xc043234410, 0xc042a5dc20)
        C:/Go/projects/goadmin/main.go:37 +0x7f
net/http.HandlerFunc.ServeHTTP(0xc042eedda0, 0xeb05a0, 0xc043234410, 0xc042a5dc2
0)
        C:/Go/src/net/http/server.go:1726 +0x4b
net/http.serverHandler.ServeHTTP(0xc042ef5180, 0xeb05a0, 0xc043234410, 0xc042a5d
c20)
        C:/Go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc042f7c780, 0xeb0ea0, 0xc042e2b600)
        C:/Go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2293 +0x454
http: panic serving 127.0.0.1:52964: reflect: Call using zero Value argument
goroutine 147 [running]:
net/http.(*conn).serve.func1(0xc042f7d480)
        C:/Go/src/net/http/server.go:1491 +0x131
panic(0xaa6d80, 0xc042b5bca0)
        C:/Go/src/runtime/panic.go:458 +0x251
reflect.Value.call(0xadf0a0, 0xc043237800, 0x213, 0xb89657, 0x4, 0xc042ff95b0, 0
x1, 0x1, 0xc042079c10, 0x13, ...)
        C:/Go/src/reflect/value.go:366 +0x1179
reflect.Value.Call(0xadf0a0, 0xc043237800, 0x213, 0xc042ff95b0, 0x1, 0x1, 0xc043
237800, 0x213, 0xb13e80)
        C:/Go/src/reflect/value.go:302 +0xab
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc042b
542d0, 0xae0ca0, 0xc0432377a0, 0x1, 0x0, 0x0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/storer.go:296 +0x727
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc042b5ac50, 0x10, 0xc042
b542d0, 0xaa6d80, 0xc042ff9780)
        C:/Go/Projects/src/github.com/qor/qor-example/config/auth/db_storer.go:3
0 +0x1cb
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0xef7298, 0xc042b5ac50,
 0x10, 0xc042b542d0, 0xc043233201, 0xc042ff9701)
        <autogenerated>:2 +0x71
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc
042c59900, 0xb8acbf, 0x5)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/context.go:109 +0xba
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confir
mHandler(0xc04220a200, 0xc042c59900, 0xeb05a0, 0xc043234d00, 0xc04328c690, 0xeaf
fe0, 0xc04304c0a0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:196 +0x608
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(githu
b.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc
042c59900, 0xeb05a0, 0xc043234d00, 0xc04328c690, 0xc042c59900, 0xc042b73e30)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:86 +0x59
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(
0xc0423d4280, 0xc042b00cc0, 0xeb05a0, 0xc043234d00, 0xc04328c690)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/router.go:58 +0x11a
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHT
TP(0xc042b00d70, 0xeb05a0, 0xc043234d00, 0xc04328c690)
        <autogenerated>:124 +0x80
net/http.(*ServeMux).ServeHTTP(0xc042b040f0, 0xeb05a0, 0xc043234d00, 0xc04328c69
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042b040c0, 0xeb05a0, 0xc043234d00, 0xc04328c69
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042af7fb0, 0xeb05a0, 0xc043234d00, 0xc04328c69
0)
        C:/Go/src/net/http/server.go:2022 +0x86
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc04317bc20, 0xeb05a0, 0xc043234d00,
0xc04328c690)
        C:/Go/Projects/src/github.com/gorilla/csrf/csrf.go:267 +0x3c1
main.main.func1.1(0xeb05a0, 0xc043234d00, 0xc0430533b0)
        C:/Go/projects/goadmin/main.go:37 +0x7f
net/http.HandlerFunc.ServeHTTP(0xc042eedda0, 0xeb05a0, 0xc043234d00, 0xc0430533b
0)
        C:/Go/src/net/http/server.go:1726 +0x4b
net/http.serverHandler.ServeHTTP(0xc042ef5180, 0xeb05a0, 0xc043234d00, 0xc043053
3b0)
        C:/Go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc042f7d480, 0xeb0ea0, 0xc042cb8cc0)
        C:/Go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2293 +0x454
http: panic serving 127.0.0.1:52965: reflect: Call using zero Value argument
goroutine 148 [running]:
net/http.(*conn).serve.func1(0xc042f7dc80)
        C:/Go/src/net/http/server.go:1491 +0x131
panic(0xaa6d80, 0xc042b41830)
        C:/Go/src/runtime/panic.go:458 +0x251
reflect.Value.call(0xadf0a0, 0xc0431f2760, 0x213, 0xb89657, 0x4, 0xc042ff95b0, 0
x1, 0x1, 0xc042079d50, 0x13, ...)
        C:/Go/src/reflect/value.go:366 +0x1179
reflect.Value.Call(0xadf0a0, 0xc0431f2760, 0x213, 0xc042ff95b0, 0x1, 0x1, 0xc043
1f2760, 0x213, 0xb13e80)
        C:/Go/src/reflect/value.go:302 +0xab
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc042b
55ef0, 0xae0ca0, 0xc0431f2700, 0x1, 0x0, 0x0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/storer.go:296 +0x727
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc042b40770, 0x10, 0xc042
b55ef0, 0xaa6d80, 0xc042ff9780)
        C:/Go/Projects/src/github.com/qor/qor-example/config/auth/db_storer.go:3
0 +0x1cb
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0xef7298, 0xc042b40770,
 0x10, 0xc042b55ef0, 0xc043233a01, 0xc042ff9701)
        <autogenerated>:2 +0x71
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc
042bd80c0, 0xb8acbf, 0x5)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/context.go:109 +0xba
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confir
mHandler(0xc04220a200, 0xc042bd80c0, 0xeb05a0, 0xc0432355f0, 0xc04328c870, 0xeaf
fe0, 0xc04304ce00)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:196 +0x608
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(githu
b.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc
042bd80c0, 0xeb05a0, 0xc0432355f0, 0xc04328c870, 0xc042bd8000, 0xc042b5bcc0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:86 +0x59
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(
0xc0423d4280, 0xc042b00cc0, 0xeb05a0, 0xc0432355f0, 0xc04328c870)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/router.go:58 +0x11a
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHT
TP(0xc042b00d70, 0xeb05a0, 0xc0432355f0, 0xc04328c870)
        <autogenerated>:124 +0x80
net/http.(*ServeMux).ServeHTTP(0xc042b040f0, 0xeb05a0, 0xc0432355f0, 0xc04328c87
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042b040c0, 0xeb05a0, 0xc0432355f0, 0xc04328c87
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042af7fb0, 0xeb05a0, 0xc0432355f0, 0xc04328c87
0)
        C:/Go/src/net/http/server.go:2022 +0x86
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc04317bc20, 0xeb05a0, 0xc0432355f0,
0xc04328c870)
        C:/Go/Projects/src/github.com/gorilla/csrf/csrf.go:267 +0x3c1
main.main.func1.1(0xeb05a0, 0xc0432355f0, 0xc042a5dd10)
        C:/Go/projects/goadmin/main.go:37 +0x7f
net/http.HandlerFunc.ServeHTTP(0xc042eedda0, 0xeb05a0, 0xc0432355f0, 0xc042a5dd1
0)
        C:/Go/src/net/http/server.go:1726 +0x4b
net/http.serverHandler.ServeHTTP(0xc042ef5180, 0xeb05a0, 0xc0432355f0, 0xc042a5d
d10)
        C:/Go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc042f7dc80, 0xeb0ea0, 0xc042e2b640)
        C:/Go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2293 +0x454
http: panic serving 127.0.0.1:52966: reflect: Call using zero Value argument
goroutine 149 [running]:
net/http.(*conn).serve.func1(0xc042f5e600)
        C:/Go/src/net/http/server.go:1491 +0x131
panic(0xaa6d80, 0xc042b19eb0)
        C:/Go/src/runtime/panic.go:458 +0x251
reflect.Value.call(0xadf0a0, 0xc042fd5b80, 0x213, 0xb89657, 0x4, 0xc0432215b0, 0
x1, 0x1, 0xc0422dd040, 0x13, ...)
        C:/Go/src/reflect/value.go:366 +0x1179
reflect.Value.Call(0xadf0a0, 0xc042fd5b80, 0x213, 0xc0432215b0, 0x1, 0x1, 0xc042
fd5b80, 0x213, 0xb13e80)
        C:/Go/src/reflect/value.go:302 +0xab
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc042b
3c7e0, 0xae0ca0, 0xc042fd5b20, 0x1, 0x0, 0x0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/storer.go:296 +0x727
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc042b18a00, 0x10, 0xc042
b3c7e0, 0xaa6d80, 0xc043221780)
        C:/Go/Projects/src/github.com/qor/qor-example/config/auth/db_storer.go:3
0 +0x1cb
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0xef7298, 0xc042b18a00,
 0x10, 0xc042b3c7e0, 0xc043226201, 0xc043221701)
        <autogenerated>:2 +0x71
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc
042cb8f40, 0xb8acbf, 0x5)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/context.go:109 +0xba
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confir
mHandler(0xc04220a200, 0xc042cb8f40, 0xeb05a0, 0xc043011ee0, 0xc043053590, 0xeaf
fe0, 0xc0430dc720)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:196 +0x608
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(githu
b.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc
042cb8f40, 0xeb05a0, 0xc043011ee0, 0xc043053590, 0xc042cb8f00, 0xc042d6dd00)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:86 +0x59
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(
0xc0423d4280, 0xc042b00cc0, 0xeb05a0, 0xc043011ee0, 0xc043053590)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/router.go:58 +0x11a
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHT
TP(0xc042b00d70, 0xeb05a0, 0xc043011ee0, 0xc043053590)
        <autogenerated>:124 +0x80
net/http.(*ServeMux).ServeHTTP(0xc042b040f0, 0xeb05a0, 0xc043011ee0, 0xc04305359
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042b040c0, 0xeb05a0, 0xc043011ee0, 0xc04305359
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042af7fb0, 0xeb05a0, 0xc043011ee0, 0xc04305359
0)
        C:/Go/src/net/http/server.go:2022 +0x86
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc04317bc20, 0xeb05a0, 0xc043011ee0,
0xc043053590)
        C:/Go/Projects/src/github.com/gorilla/csrf/csrf.go:267 +0x3c1
main.main.func1.1(0xeb05a0, 0xc043011ee0, 0xc04328c960)
        C:/Go/projects/goadmin/main.go:37 +0x7f
net/http.HandlerFunc.ServeHTTP(0xc042eedda0, 0xeb05a0, 0xc043011ee0, 0xc04328c96
0)
        C:/Go/src/net/http/server.go:1726 +0x4b
net/http.serverHandler.ServeHTTP(0xc042ef5180, 0xeb05a0, 0xc043011ee0, 0xc04328c
960)
        C:/Go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc042f5e600, 0xeb0ea0, 0xc042bd8440)
        C:/Go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2293 +0x454
http: panic serving 127.0.0.1:52967: reflect: Call using zero Value argument
goroutine 161 [running]:
net/http.(*conn).serve.func1(0xc043007b00)
        C:/Go/src/net/http/server.go:1491 +0x131
panic(0xaa6d80, 0xc042b01690)
        C:/Go/src/runtime/panic.go:458 +0x251
reflect.Value.call(0xadf0a0, 0xc043302ae0, 0x213, 0xb89657, 0x4, 0xc0432215b0, 0
x1, 0x1, 0xc0422dd1f0, 0x13, ...)
        C:/Go/src/reflect/value.go:366 +0x1179
reflect.Value.Call(0xadf0a0, 0xc043302ae0, 0x213, 0xc0432215b0, 0x1, 0x1, 0xc043
302ae0, 0x213, 0xb13e80)
        C:/Go/src/reflect/value.go:302 +0xab
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.Attributes.Bind(0xc042b
1ec90, 0xae0ca0, 0xc043302a80, 0x1, 0x0, 0x0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/storer.go:296 +0x727
github.com/qor/qor-example/config/auth.AuthStorer.Put(0xc042b00970, 0x10, 0xc042
b1ec90, 0xaa6d80, 0xc043221780)
        C:/Go/Projects/src/github.com/qor/qor-example/config/auth/db_storer.go:3
0 +0x1cb
github.com/qor/qor-example/config/auth.(*AuthStorer).Put(0xef7298, 0xc042b00970,
 0x10, 0xc042b1ec90, 0xc043226a01, 0xc043221701)
        <autogenerated>:2 +0x71
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*Context).SaveUser(0xc
042cb96c0, 0xb8acbf, 0x5)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/context.go:109 +0xba
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).confir
mHandler(0xc04220a200, 0xc042cb96c0, 0xeb05a0, 0xc043228820, 0xc043053770, 0xeaf
fe0, 0xc0430dd4a0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:196 +0x608
github.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.(*Confirm).(githu
b.com/qor/qor-example/vendor/gopkg.in/authboss.v0/confirm.confirmHandler)-fm(0xc
042cb96c0, 0xeb05a0, 0xc043228820, 0xc043053770, 0xc042cb9600, 0xc042b19ee0)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/confirm/confirm.go:86 +0x59
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.contextRoute.ServeHTTP(
0xc0423d4280, 0xc042b00cc0, 0xeb05a0, 0xc043228820, 0xc043053770)
        C:/Go/Projects/src/github.com/qor/qor-example/vendor/gopkg.in/authboss.v
0/router.go:58 +0x11a
github.com/qor/qor-example/vendor/gopkg.in/authboss%2ev0.(*contextRoute).ServeHT
TP(0xc042b00d70, 0xeb05a0, 0xc043228820, 0xc043053770)
        <autogenerated>:124 +0x80
net/http.(*ServeMux).ServeHTTP(0xc042b040f0, 0xeb05a0, 0xc043228820, 0xc04305377
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042b040c0, 0xeb05a0, 0xc043228820, 0xc04305377
0)
        C:/Go/src/net/http/server.go:2022 +0x86
net/http.(*ServeMux).ServeHTTP(0xc042af7fb0, 0xeb05a0, 0xc043228820, 0xc04305377
0)
        C:/Go/src/net/http/server.go:2022 +0x86
github.com/gorilla/csrf.(*csrf).ServeHTTP(0xc04317bc20, 0xeb05a0, 0xc043228820,
0xc043053770)
        C:/Go/Projects/src/github.com/gorilla/csrf/csrf.go:267 +0x3c1
main.main.func1.1(0xeb05a0, 0xc043228820, 0xc04328ca50)
        C:/Go/projects/goadmin/main.go:37 +0x7f
net/http.HandlerFunc.ServeHTTP(0xc042eedda0, 0xeb05a0, 0xc043228820, 0xc04328ca5
0)
        C:/Go/src/net/http/server.go:1726 +0x4b
net/http.serverHandler.ServeHTTP(0xc042ef5180, 0xeb05a0, 0xc043228820, 0xc04328c
a50)
        C:/Go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc043007b00, 0xeb0ea0, 0xc042bd8480)
        C:/Go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
        C:/Go/src/net/http/server.go:2293 +0x454

However during clicking the confirm link from email, got "Problem loading page..." The connection was reset.

Thanks

**Comment by aarondl** [comment]
There was actually a fix for this exact same error message just pushed today. If you have sql null types (ie. sql.NullString) in your model it's very possible this is the same problem. Can you fetch the latest master (tag v1.0.2) and try again?

If not, I'm afraid I'll have to ask for more information. Since it's sample code, maybe you could just zip it up and send it to me. Past that I'd need to see what the request to the server is, and what any Storer models fetched look like (you can put a Print statement in where your `Storer` does the `.Get()`)

**Comment by aarondl** [comment]
Stale.
