### ISSUE TITLE
func Bind (storer.go) does not handle sql.NullString type properly "reflect: Call using zero Value argument"

### ISSUE THREAD

**Issue by sunwukonga** [go-authboss/authboss#110]
Unbind stores sql.Nullstring{String:"", Valid:false} as nil into Attributes map through func (ns *Nullstring) Value(...) method in database/sql.

When Bind makes a subsequent call to reflect.ValueOf(...) it panics on this nil interaface{} value, with "reflect: Call using zero Value argument".

I got around this by wrapping the following code in storer.go with a test for nil,
```
    if v != nil {
        rvals := method.Call([]reflect.Value{reflect.ValueOf(v)})
        if err, ok := rvals[0].Interface().(error); ok && err != nil {
            return err
        }
    }
```
This works for all of
```
    sql.NullString
    sql.NullInt64
    sql.NullFloat64
    sql.NullBool 
```
returns the appropriate sql.NullString{String:"", Valid:false} when the map interface value is nil.

I use authboss through the vendor directory (`authboss.v0`), and not knowing if there are other work arounds for this, whether it is cleared up in a v2, or even if my solution is inappropriate; I just thought I'd put my experience here and let you sort it out.

**Comment by sunwukonga** [comment]
https://play.golang.org/p/4Oio9netkx

**Comment by aarondl** [comment]
This is actually going to change in v2 since the storers are being completely revamped. Part of the pain of v1 is this constant back and forth between a map of attributes and structs. The types fall apart and it's difficult to deal with. Thanks for reporting it. Would you like to submit your fix as a PR?

**Comment by aarondl** [comment]
Thanks a lot :)
