### ISSUE TITLE
fasthttp support

### ISSUE THREAD

**Issue by arafath-mk** [go-authboss/authboss#113]
Please support [fasthttp](https://github.com/valyala/fasthttp). I have been using authboss. But, all of my recent projects are being developed using fasthttp instead of net/http. It would be great if you provide support for fasthttp too.

**Comment by aarondl** [comment]
So I thought about this a bit, but I don't think fasthttp is something I'm looking to especially support. It'll take extra development and is pretty much a non-goal. If you'd like to use authboss and even authboss v2 with fasthttp it'll probably have to be a fork. They don't even support HTTP2 so I'm still not sure why people would want to use it in the kind of sites that Authboss is intended to be used by.
