### ISSUE TITLE
Namespacing users?

### ISSUE THREAD

**Issue by pcman312** [go-authboss/authboss#114]
I just came across this library, so forgive me if this question has already been answered. Is there any capability or v2 plan for adding namespacing to users? The use case I have is where I need to be able to have separate namespaces around users that allow for multiple users having the same username but under different namespaces.

Example:
namespace1/user1
namespace1/user2
namespace2/user1
namespace2/user2

**Comment by aarondl** [comment]
Hey there. Since authboss is sort of like a whole website unto itself, you could instantiate it several times and put each one behind a different set of routes. This should be possible, if you try it and it's not we'll see what we can do :)

**Comment by aarondl** [comment]
Closing as I think this is totally possible. Let me know if you run into problems with the above approach.
