### ISSUE TITLE
Panic when template cannot be found

### ISSUE THREAD

**Issue by pablopalacios** [go-authboss/authboss#116]
At this [line](https://github.com/go-authboss/authboss/blob/master/internal/response/response.go#L77) within internal/response.go a panic occurs if the template does not exist. Since template cannot be retrieved from map, `tpl` value will be `nil` and, therefore, it has no `Name()` method which causes the panic.

I think the right fix here is to replace `tpl.Name()` for just `name` which is the name that didn't retrieved any result.

**Comment by aarondl** [comment]
Oh yeah. That's a pretty short-sighted thing to do. Would you like to make a pull request to be among the contributors on Github? Or should I do the change?
