### ISSUE TITLE
Resend confirmation link

### ISSUE THREAD

**Issue by kaiomagalhaes** [go-authboss/authboss#120]
Hey @aarondl , here at my organization we are using authboss, but we need the resend confirmation link. 

As it doesn't offer this option today I've implemented it here: https://github.com/codelittinc/authboss/commit/57210f31e4bc43c4c7f232f579963d6136e35685

If you feel that it could be useful for anyone I can update the docs and prepare a proper pull request.

**Comment by kaiomagalhaes** [comment]
@aarondl we plan to use Authboss for all of our applications in my organization and I'm very interested in help with the development of it. Please let me know if you can use some help.

**Comment by aarondl** [comment]
The functionality itself seems like a great addition to Authboss. I'd have to review the code to make sure it fits nicely but pending any nits in code review I'd be very grateful to have that functionality.

Full time job + other open source efforts go to say I could definitely use help! @kris-runzer has been occupied by many many other things and so he hasn't been able to be active lately.
I'm in the middle of a rewrite of this library. The so-called v2. There has been some work pushed to the `dev` branch and I intend to get back to it soon. The concepts and interfaces are shaping up very nicely and I'm excited for it. It looks to solve many of the problems v1 brings (and as always, bring some new problems along with it). The main reason I'm mentioning this is it's not backwards compatible :(

I'll close this issue in hopes that one day a PR will appear :)
