### ISSUE TITLE
Allow to create an after registration callback

### ISSUE THREAD

**Issue by kaiomagalhaes** [go-authboss/authboss#127]
@aarondl is there any way to create an after registration callback? If not what do you think about adding it?  I can work on it after we define the best way.

**Comment by aarondl** [comment]
There's already one here:
https://github.com/go-authboss/authboss/blob/master/callbacks.go#L16
https://github.com/go-authboss/authboss/blob/master/register/register.go#L143

You should be able to use it with no problems :) Re-open if it's insufficient.
