### ISSUE TITLE
Is gopkgin/authboss.v1  built from github.com/go-authboss/authboss ?

### ISSUE THREAD

**Issue by goodforever** [go-authboss/authboss#145]
I think gopkgin/authboss.v1 is built from github.com/go-authboss/authboss , Why does the github.com/go-authboss/authboss need import gopkg.in/authboss.v1 ?
What relation is gopkg.in/authboss.v1 to  github.com/go-authboss/authboss ?

**Comment by aarondl** [comment]
Hey there. Sorry for late response, was on vacation. Yes it is built from `github.com/go-authboss/authboss`. This should be fairly clear from the `gopkg.in` normal behaviors. It's meant to be imported as `gopkg.in/authboss.v1` but this will be changing for v2. Let me know if this clears things up.

**Comment by goodforever** [comment]
I think this is strange , When I build github.com/go-authboss/authboss ,I find it's miss gopkg.in/authboss.v1.  So I think it's better that import github.com/go-authboss/authboss.

**Comment by aarondl** [comment]
The idea is to not clone this repository into `$GOPATH/src/github.com/go-authboss/authboss` but instead into `$GOPATH/src/gopkg.in/authboss.v1`, if you are doing it the first way then it's incorrect. It seems like you're not familiar with how gopkg.in works. It's a versioning mechanism for Go code, you can read about it here: http://labix.org/gopkg.in

Packages that use gopkg.in are made for use with `go get` and not a direct `git clone` into the repository-named directory.

**Comment by goodforever** [comment]
Thanks, I don't know the gopkg.in can be used for versioning mechanism.
