### ISSUE TITLE
Did we forget a use case for editing users?

### ISSUE THREAD

**Issue by aarondl** [go-authboss/authboss#50]
How do users reset their password in a normal flow? Do they really have to go through recover and getting e-mails etc? Or are we leaving all user editing up to the other person, who then now has to know about authboss semantics such as if you update a password it should invalidate all remember me tokens, and bcrypt the password with the correct configured strength.

**Comment by kris-runzer** [comment]
Last time we discussed this we said user management was the implementers problem.  That being said, we didn't have the issue of clearing tokens.  As for the password, I think that is easy for them to solve/configure properly.

We can either implement this or setup some funcs they need to call when they implement it.

**Comment by aarondl** [comment]
Reset Password function incoming.
