### ISSUE TITLE
SMS Registrations

### ISSUE THREAD

**Issue by xi3** [go-authboss/authboss#55]
rt.

**Comment by aarondl** [comment]
I've split this into two parts #56 is about supporting mobile views by adjusting the view depending on useragent/some cookie/anything else.

This issue will continue discussion on the SMS Registration feature. I'd like to know exactly what you are expecting. Is it sending a confirmation code via SMS after account registration?

**Comment by kris-runzer** [comment]
https://github.com/giano/devise_sms_activable?

**Comment by aarondl** [comment]
@xi3 Honestly. I think this feature is beyond the scope of Authboss itself. Feel free to create a module that can do this. Looking at the source code for the confirm module you should be able to figure out how to accomplish this. If you need any help, please visit our gitter if you have questions and we'll support the effort to develop this third party module.

You can find our gitter here: https://gitter.im/go-authboss/authboss
