### ISSUE TITLE
"Internal server error" when logging in as non-existent user

### ISSUE THREAD

**Issue by alphacrowd** [go-authboss/authboss#64]
The Storer interface's Get method says (in comment) to return (nil, ErrUserNotFound) when the user is not found.  

However, this causes the auth module to display an Internal server error, instead of 
fmt.Sprintf("invalid %s and/or password", a.PrimaryID)

If it is a bug, I'd happily fix it and do a pull request.

**Comment by aarondl** [comment]
Definitely a bug. Will get fixed soon. (Hopefully by tomorrow). Thanks for the report!

**Comment by aarondl** [comment]
Sorry this took so long to fix. Thanks for reporting it!

**Comment by alphacrowd** [comment]
Thanks for fixing it and no worries about the delay !   Feel free to be in touch if you need help with enhancements / bug fixes when you're overloaded - perhaps I can fit in a bit here and there.
