### ISSUE TITLE
New field on registration form.

### ISSUE THREAD

**Issue by NCSantos** [go-authboss/authboss#68]
Hi,

If I insert a new field on registration form:
```
<div class="form-group {{with .errs}}{{with $errlist := index . "newfield"}}has-error{{end}}{{end}}">
	<input type="text" class="form-control" name="newfield" placeholder="Newfield" value="{{.newfield}}" />
	{{with .errs}}{{with $errlist := index . "newfield"}}{{range $errlist}}<span class="help-block">{{.}}</span>{{end}}{{end}}{{end}}
</div>
```
And add on Policies:
```
authboss.Rules{
	FieldName: "newfield",
	Required:  true,
	MinLength: 4,
	MaxLength: 8,
},
```
If the form has errors it doesn't return the newfield with the old value.

Am I doing something wrong or is there a way to solve this?

Thanks.

**Comment by NCSantos** [comment]
Sorry,

Found it, need to set "PreserveFields".

Thanks.

**Comment by aarondl** [comment]
@NCSantos try to open issues only for actual bug reports that you've confirmed or feature requests. If you are just stuck, have questions or otherwise please use gitter to chat with us. https://gitter.im/go-authboss/authboss
