### ISSUE TITLE
Redundant code in oauth.

### ISSUE THREAD

**Issue by orian** [go-authboss/authboss#71]
https://github.com/go-authboss/authboss/blob/master/oauth2/providers.go#L13
GoogleEndpoints duplicates:
https://godoc.org/golang.org/x/oauth2/google#pkg-variables Endpoint variable.

(btw i've tested the code with Facebook login, works flawlessly)

```go
type facebookMeResponse struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

const (
	facebookInfoEndpoint = "https://graph.facebook.com/me"
)

// Facebook is a callback appropriate for use with Facebook's OAuth2 configuration.
func Facebook(cfg oauth2.Config, token *oauth2.Token) (authboss.Attributes, error) {
	client := cfg.Client(oauth2.NoContext, token)
	resp, err := client.Get(facebookInfoEndpoint)
	if err != nil {
		return nil, err
	}

	defer resp.Body.Close()
	dec := json.NewDecoder(resp.Body)
	var jsonResp facebookMeResponse
	if err = dec.Decode(&jsonResp); err != nil {
		return nil, err
	}

	return authboss.Attributes{
		"name":                  jsonResp.Name,
		authboss.StoreOAuth2UID: jsonResp.ID,
		authboss.StoreEmail:     jsonResp.Email,
	}, nil
}
```

**Comment by aarondl** [comment]
This duplication was intentional to avoid having to import other packages :)

**Comment by orian** [comment]
But `golang.org/x/oauth2` is imported anyway (thus must be installed) so I think it makes more sense to just add `golang.org/x/oauth2/google`.

**Comment by aarondl** [comment]
The idea was that I needed test data, also I wanted to support Google auth directly.

https://github.com/go-authboss/authboss/blob/master/oauth2/oauth2_test.go#L25

I've either got some meaningless test data there, or that Google struct. It's not a big deal regardless. If it were actual code I'd definitely remove it, but a constant struct isn't very serious.

**Comment by aarondl** [comment]
Actually, looking at this again you're totally right. I'll fix this soon.

Also, would you like to pull request your Facebook provider?
