### ISSUE TITLE
Implementing custom login/logout

### ISSUE THREAD

**Issue by bunnyfly** [go-authboss/authboss#73]
If I want to implement a custom API (vs form) call that a web app can call to log in or out, it seems I will have to copy/paste most of the [auth package](https://github.com/go-authboss/authboss/blob/master/auth/auth.go#L82) into my own code. Is there a better way? Seems like authboss.Login(...) etc would be very useful methods, but maybe there is already a way to do this?

Btw - thank you for the excellent library :)

**Comment by aarondl** [comment]
Hi bunnyfly.

This is actually sort of an oversight from an architecture/design standpoint and we're kicking ourselves for it now and have been saying this for a while now.

When we made authboss, what we should have done was create a library that had the basic tools like sending out e-mails, generating tokens, passwords etc that could have been decoupled from the actual authboss implementation which is sort of a "half of a server-side rendering web app".

We aimed to port Devise to Go and in that I think we've largely succeeded. But what we didn't take a look at is: during this porting, what could we improve?

We're definitely looking at pulling this functionality out into a library, but lack the time currently and so it doesn't seem to be a change that will land in the near future. Sorry :(
