### ISSUE TITLE
InternalServerError if user not found

### ISSUE THREAD

**Issue by orian** [go-authboss/authboss#75]
If a user has a proper cookie but the user has been deleted from a DB (authboss.Storer) it returns 500 Internal Server Error.

https://github.com/go-authboss/authboss/blob/61a344b75a5c39e69a970bc619f48dacba9d336a/router.go#L118

Maybe it should be considered to remove such cookie?

**Comment by aarondl** [comment]
Will see about a fix soon :)

**Comment by orian** [comment]
Another problem:

 - have some cookie (but cannot fetch session)
 - go to /auth/recover,
 - click on link in email /auth/recover/complete
 - instead of password change, the page redirects (checked, no error handler register in authboss conf has been called).

**Comment by aarondl** [comment]
Hey @orian, it now removes the cookie. I couldn't fully understand your second comment, but I'm assuming that it goes away with this fix. If not, please re-open or submit another issue. Thanks!
