### ISSUE TITLE
Disabling views - returning only JSON responses

### ISSUE THREAD

**Issue by o-r-r** [go-authboss/authboss#80]
Is it possible to disable the views parts after login, logout, etc. and just return a JSON response and let the web client handle the views itself?
Thanks

**Comment by aarondl** [comment]
It's not actually possible in Authboss's current state. It's an unfortunate oversight. We really built it with the "Devise" solution in mind which is the views are done for you, etc.

Both myself and @kris-runzer agree that Authboss needs a refactoring to be able to pull out the various pieces: auth itself, token generation, views - into separate pieces. This would allow us to help out those with SPA-style pages as well as the server side rendering crowd. A much more take-what-you-need approach.

More unfortunate than having not made it that way in the first place, is that we don't have enough time to recreate Authboss in that image currently. That means; it's planned - but don't hold your breath :(

**Comment by ernsheong** [comment]
@aarondl is this still true today in v2?

**Comment by aarondl** [comment]
@ernsheong Nope. Lots of the reason behind v2 was to absract the HTTP stack and let you make it behave as you want it to. Now it renders and responds how you tell it to in v2. There are interfaces in the config, namely:

```text
authboss.Config.Core.ErrorHandler
authboss.Config.Core.Responder
authboss.Config.Core.Redirector
authboss.Config.Core.ViewRenderer
```

These control what gets back to the user's browser.

The `defaults` package implements many things that are JSON-aware including:

* [Renderer](https://github.com/volatiletech/authboss/blob/v2/defaults/renderer.go)
* [Responder & Redirector](https://github.com/volatiletech/authboss/blob/v2/defaults/responder.go)

**Comment by ernsheong** [comment]
@aarondl thanks for the response!
