### ISSUE TITLE
Trouble setting up

### ISSUE THREAD

**Issue by AlbinOS** [go-authboss/authboss#86]
I'm trying to start using Authboss in my Gin based Go web application but I have some trouble to set it up. I've read and tried to copy paste from the sample project. Here is the code that I use :

```go
package main

import (
	// Authboss
	"log"
	"net/http"
	"os"

	unleashAuth "github.com/GoPex/unleash/auth"
	"github.com/justinas/nosurf"
	"gopkg.in/authboss.v0"
	_ "gopkg.in/authboss.v0/auth"
	_ "gopkg.in/authboss.v0/register"
)

func main() {
	// Authboss
	ab := authboss.New() // Usually store this globally
	ab.MountPath = "/auth"
	ab.LogWriter = os.Stdout
	ab.Storer = unleashAuth.NewMemStorer()

	ab.XSRFName = "csrf_token"
	ab.XSRFMaker = func(_ http.ResponseWriter, r *http.Request) string {
		return nosurf.Token(r)
	}

	ab.CookieStoreMaker = unleashAuth.NewCookieStorer
	ab.SessionStoreMaker = unleashAuth.NewSessionStorer

	if err := ab.Init(); err != nil {
		log.Fatalln(err)
	}

	http.Handle("/auth", ab.NewRouter())
	http.ListenAndServe(":8080", nil)
}
```

[NewMemStorer](https://github.com/go-authboss/authboss-sample/blob/master/storer.go), [NewCookieStorer](https://github.com/go-authboss/authboss-sample/blob/master/cookie_storer.go) and [NewSessionStorer](https://github.com/go-authboss/authboss-sample/blob/master/session_storer.go) are coming from the [sample project](https://github.com/go-authboss/authboss).

My problem is that when I try to reach `http://localhost:8080/auth/register`, I have a `404` response...

Any idea ? 

Thanks a lot,
Albin.

**Comment by aarondl** [comment]
https://github.com/go-authboss/authboss/wiki/Integration-with-gin-gonic

Have you seen this?

**Comment by AlbinOS** [comment]
Ah... no.

I guess I'll have on look on this first then ! 

Thanks and sorry, my Google skills still needs some training obviously.
