### ISSUE TITLE
register doesn't assert SessionStoreMaker and CookieStoreMaker are non-nil

### ISSUE THREAD

**Issue by yargevad** [go-authboss/authboss#87]
This results in a panic for any hit on `/register`.

**Comment by aarondl** [comment]
From the docs in the config object:
https://github.com/go-authboss/authboss/blob/master/config.go

```go
// CookieStoreMaker must be defined to provide an interface capapable of storing cookies
// for the given response, and reading them from the request.
CookieStoreMaker CookieStoreMaker
// SessionStoreMaker must be defined to provide an interface capable of storing session-only
// values for the given response, and reading them from the request
SessionStoreMaker SessionStoreMaker
```

*Must be defined* - The panic is completely intentional as Authboss cannot function without the concepts of sessions and cookies.

**Comment by yargevad** [comment]
Oops, didn't reference my PR: in #88 I added a failure to startup when either of those things are missing, in addition to the panic.
