### ISSUE TITLE
Accessing /auth/login as a logged in user always redirects to AuthLoginOKPath

### ISSUE THREAD

**Issue by jack-chung** [go-authboss/authboss#89]
Using the sample app as an example, first log in with a valid credential. Then manually go to http://localhost:3000/auth/login and you will be redirected to AuthLoginOKPath instead of seeing the login form. POSTing an invalid credential to /auth/login (when you are already logged in) also result in redirecting to AuthLoginOKPath instead of seeing an error message.

This may not be a bug per se as it won't let you log in as someone else. It just keeps you in your own valid session. However the behavior is a little unexpected so it'd be good to get some clarification on whether this is intended behavior.

**Comment by aarondl** [comment]
I'm curious what the behavior should be. What would you view as proper in
this situation? We could dump them at OK path with a: You are already
logged in. Could also log them out as it might be some sort of strange
attack (after all how did they find the login page while logged in and why
are they posting to it?)

What do you think?

**Comment by jack-chung** [comment]
I think showing the login form and processing the auth POST as if this is coming from a person not logged in would be good. This can be the basis of some kind of account switching feature.

Another use case is that we can use this to ask for extra authentication before allowing risky actions such as changing the account email address.

**Comment by jack-chung** [comment]
Hi @aarondl I am facing another problem, likely due to this behavior. I want to allow users (who are already logged in via email-based accounts) to also "link" their Facebook accounts. For this, I want to redirect logged in users to /auth/oauth/ so they can give the consent. However, authboss redirects users back to AuthLoginOKPath and not to Facebook.

**Comment by jack-chung** [comment]
I am able to implement account linking by working around this behaviour, so this is no longer a blocker.

**Comment by aarondl** [comment]
Not going to change this behavior. Talked to @jack-chung on gitter, he says he's okay with the current functionality.
